// Mock data for development
// This file contains all mock data that simulates API responses
import type { OverviewStat, Platform, TopContent, Campaign, Creator, Payment, Asset } from '../types';

export const mockOverviewStats: OverviewStat[] = [
  {
    title: 'Total Views',
    value: '12.4M',
    change: '+18%',
    changeType: 'positive',
    icon: 'Eye',
    color: 'blue',
  },
  {
    title: 'Total Spend',
    value: '$89,420',
    change: '+12%',
    changeType: 'positive',
    icon: 'DollarSign',
    color: 'green',
  },
  {
    title: 'Avg. CPM',
    value: '$4.20',
    change: '-8%',
    changeType: 'negative',
    icon: 'TrendingDown',
    color: 'purple',
  },
  {
    title: 'Active Creators',
    value: '32',
    change: '+5',
    changeType: 'positive',
    icon: 'Users',
    color: 'orange',
  },
];

export const mockDashboardStats: OverviewStat[] = [
  {
    title: 'Active Campaigns',
    value: '12',
    change: '+3',
    changeType: 'positive',
    icon: 'Target',
    color: 'purple',
  },
  {
    title: 'Total Spend',
    value: '$45,230',
    change: '+12%',
    changeType: 'positive',
    icon: 'DollarSign',
    color: 'green',
  },
  {
    title: 'Total Views',
    value: '2.4M',
    subtitle: 'Avg CPM: $4.20',
    change: '-4%',
    changeType: 'negative',
    icon: 'Eye',
    color: 'blue',
  },
  {
    title: 'New Videos',
    value: '48',
    change: '+8',
    changeType: 'positive',
    icon: 'Video',
    color: 'orange',
  },
];

export const mockPlatformData: Platform[] = [
  { name: 'YouTube', views: '6.2M', spend: '$42,000', cpm: '$3.80', color: 'bg-red-500' },
  { name: 'TikTok', views: '4.1M', spend: '$28,000', cpm: '$4.20', color: 'bg-gray-900' },
  { name: 'Instagram', views: '2.1M', spend: '$19,420', cpm: '$5.10', color: 'bg-gradient-to-r from-purple-500 to-pink-500' },
];

export const mockTopContent: TopContent[] = [
  { title: 'Product Launch Video', creator: 'Alex Johnson', views: '1.2M', engagement: '8.4%' },
  { title: 'Tutorial Series Ep.1', creator: 'Sarah Miller', views: '890K', engagement: '7.2%' },
  { title: 'Brand Story Documentary', creator: 'Mike Chen', views: '756K', engagement: '9.1%' },
  { title: 'Customer Testimonial', creator: 'Emily Davis', views: '654K', engagement: '6.8%' },
  { title: 'Behind the Scenes', creator: 'David Kim', views: '542K', engagement: '8.9%' },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    name: 'Summer Product Launch',
    platform: 'YouTube',
    status: 'Active',
    budget: '$5,000',
    spent: '$3,240',
    views: '450K',
    creators: 8,
    startDate: 'Jan 15, 2026',
    endDate: 'Feb 15, 2026',
  },
  {
    id: 2,
    name: 'Brand Awareness Q1',
    platform: 'TikTok',
    status: 'Active',
    budget: '$10,000',
    spent: '$7,890',
    views: '1.2M',
    creators: 15,
    startDate: 'Jan 1, 2026',
    endDate: 'Mar 31, 2026',
  },
  {
    id: 3,
    name: 'Holiday Special Promo',
    platform: 'Instagram',
    status: 'Completed',
    budget: '$8,000',
    spent: '$8,000',
    views: '890K',
    creators: 12,
    startDate: 'Dec 1, 2025',
    endDate: 'Dec 31, 2025',
  },
  {
    id: 4,
    name: 'New Feature Announcement',
    platform: 'YouTube',
    status: 'Draft',
    budget: '$3,500',
    spent: '$0',
    views: '0',
    creators: 5,
    startDate: 'Feb 10, 2026',
    endDate: 'Feb 28, 2026',
  },
  {
    id: 5,
    name: 'Customer Testimonials',
    platform: 'Multiple',
    status: 'Paused',
    budget: '$6,000',
    spent: '$2,100',
    views: '320K',
    creators: 6,
    startDate: 'Jan 5, 2026',
    endDate: 'Feb 5, 2026',
  },
];

export const mockRecentCampaigns: Campaign[] = [
  {
    id: 1,
    name: '10 Simple steps to revolutionise workflows with our product',
    platform: 'facebook',
    status: 'Draft',
    startDate: 'Not Started',
    endDate: null,
    lastUpdated: 'Apr 10, 2023',
    progress: 0,
    avatars: [
      'https://i.pravatar.cc/32?img=1',
      'https://i.pravatar.cc/32?img=2',
      'https://i.pravatar.cc/32?img=3',
    ],
  },
  {
    id: 2,
    name: 'Boost your performance: start using our amazing product',
    platform: 'google',
    status: 'In Progress',
    startDate: 'Jun 1, 2023',
    endDate: 'Aug 1, 2023',
    lastUpdated: 'July 10, 2023',
    progress: 65,
    avatars: ['https://i.pravatar.cc/32?img=4'],
  },
  {
    id: 3,
    name: 'The power of our product: A new era in SaaS',
    platform: 'google',
    status: 'Archived',
    startDate: null,
    endDate: 'Jun 11, 2023',
    lastUpdated: 'Apr 10, 2023',
    progress: 100,
    avatars: [
      'https://i.pravatar.cc/32?img=5',
      'https://i.pravatar.cc/32?img=6',
      'https://i.pravatar.cc/32?img=7',
    ],
  },
];

export const mockCreators: Creator[] = [
  {
    id: 1,
    name: 'Alex Johnson',
    handle: '@alexjohnson',
    avatar: 'https://i.pravatar.cc/80?img=10',
    platform: 'YouTube',
    subscribers: '2.4M',
    avgViews: '450K',
    rating: 4.9,
    campaigns: 12,
    status: 'Active',
  },
  {
    id: 2,
    name: 'Sarah Miller',
    handle: '@sarahmiller',
    avatar: 'https://i.pravatar.cc/80?img=11',
    platform: 'TikTok',
    subscribers: '1.8M',
    avgViews: '980K',
    rating: 4.8,
    campaigns: 8,
    status: 'Active',
  },
  {
    id: 3,
    name: 'Mike Chen',
    handle: '@mikechen',
    avatar: 'https://i.pravatar.cc/80?img=12',
    platform: 'YouTube',
    subscribers: '3.2M',
    avgViews: '756K',
    rating: 4.7,
    campaigns: 15,
    status: 'Active',
  },
  {
    id: 4,
    name: 'Emily Davis',
    handle: '@emilydavis',
    avatar: 'https://i.pravatar.cc/80?img=13',
    platform: 'Instagram',
    subscribers: '890K',
    avgViews: '120K',
    rating: 4.6,
    campaigns: 6,
    status: 'Pending',
  },
  {
    id: 5,
    name: 'David Kim',
    handle: '@davidkim',
    avatar: 'https://i.pravatar.cc/80?img=14',
    platform: 'YouTube',
    subscribers: '1.5M',
    avgViews: '320K',
    rating: 4.5,
    campaigns: 9,
    status: 'Active',
  },
  {
    id: 6,
    name: 'Lisa Wang',
    handle: '@lisawang',
    avatar: 'https://i.pravatar.cc/80?img=15',
    platform: 'TikTok',
    subscribers: '4.1M',
    avgViews: '1.2M',
    rating: 4.9,
    campaigns: 20,
    status: 'Active',
  },
];

export const mockTopCreators = [
  { name: 'Alex Johnson', views: '1.2M', avatar: 'https://i.pravatar.cc/40?img=10' },
  { name: 'Sarah Miller', views: '980K', avatar: 'https://i.pravatar.cc/40?img=11' },
  { name: 'Mike Chen', views: '756K', avatar: 'https://i.pravatar.cc/40?img=12' },
  { name: 'Emily Davis', views: '654K', avatar: 'https://i.pravatar.cc/40?img=13' },
];

export const mockPayments: Payment[] = [
  {
    id: 1,
    creator: 'Alex Johnson',
    avatar: 'https://i.pravatar.cc/40?img=10',
    amount: '$5,240',
    campaign: 'Summer Product Launch',
    status: 'Paid',
    date: 'Jan 28, 2026',
    method: 'Bank Transfer',
  },
  {
    id: 2,
    creator: 'Sarah Miller',
    avatar: 'https://i.pravatar.cc/40?img=11',
    amount: '$3,890',
    campaign: 'Brand Awareness Q1',
    status: 'Pending',
    date: 'Feb 5, 2026',
    method: 'PayPal',
  },
  {
    id: 3,
    creator: 'Mike Chen',
    avatar: 'https://i.pravatar.cc/40?img=12',
    amount: '$4,200',
    campaign: 'Holiday Special Promo',
    status: 'Processing',
    date: 'Feb 1, 2026',
    method: 'Bank Transfer',
  },
  {
    id: 4,
    creator: 'Emily Davis',
    avatar: 'https://i.pravatar.cc/40?img=13',
    amount: '$2,100',
    campaign: 'Customer Testimonials',
    status: 'Paid',
    date: 'Jan 25, 2026',
    method: 'Stripe',
  },
  {
    id: 5,
    creator: 'David Kim',
    avatar: 'https://i.pravatar.cc/40?img=14',
    amount: '$1,850',
    campaign: 'New Feature Announcement',
    status: 'Failed',
    date: 'Jan 30, 2026',
    method: 'PayPal',
  },
];

export const mockAssets: Asset[] = [
  {
    id: 1,
    title: 'Product Launch Announcement',
    name: 'Product Launch Video.mp4',
    type: 'video',
    size: '124 MB',
    creator: 'Alex Johnson',
    avatar: 'https://i.pravatar.cc/40?img=10',
    thumbnail: 'https://picsum.photos/seed/1/400/225',
    platform: 'YouTube',
    views: '1.2M',
    uploadDate: 'Jan 15, 2026',
    uploadedAt: 'Jan 15, 2026',
    uploadedBy: 'Alex Johnson',
    status: 'Published',
    duration: '10:24',
    campaign: 'Summer Product Launch',
  },
  {
    id: 2,
    title: 'Tutorial: Getting Started',
    name: 'Tutorial Video.mp4',
    type: 'video',
    size: '45 MB',
    creator: 'Sarah Miller',
    avatar: 'https://i.pravatar.cc/40?img=11',
    thumbnail: 'https://picsum.photos/seed/2/400/225',
    platform: 'TikTok',
    views: '890K',
    uploadDate: 'Jan 18, 2026',
    uploadedAt: 'Jan 18, 2026',
    uploadedBy: 'Sarah Miller',
    status: 'Published',
    duration: '0:58',
    campaign: 'Brand Awareness Q1',
  },
  {
    id: 3,
    title: 'Behind the Scenes',
    name: 'BTS Documentary.mp4',
    type: 'video',
    size: '210 MB',
    creator: 'Mike Chen',
    avatar: 'https://i.pravatar.cc/40?img=12',
    thumbnail: 'https://picsum.photos/seed/3/400/225',
    platform: 'YouTube',
    views: '756K',
    uploadDate: 'Jan 20, 2026',
    uploadedAt: 'Jan 20, 2026',
    uploadedBy: 'Mike Chen',
    status: 'Published',
    duration: '15:32',
    campaign: 'Holiday Special Promo',
  },
  {
    id: 4,
    title: 'Customer Success Story',
    name: 'Testimonial.mp4',
    type: 'video',
    size: '67 MB',
    creator: 'Emily Davis',
    avatar: 'https://i.pravatar.cc/40?img=13',
    thumbnail: 'https://picsum.photos/seed/4/400/225',
    platform: 'Instagram',
    views: '0',
    uploadDate: 'Feb 5, 2026',
    uploadedAt: 'Feb 5, 2026',
    uploadedBy: 'Emily Davis',
    status: 'Draft',
    duration: '1:45',
    campaign: 'Customer Testimonials',
  },
  {
    id: 5,
    title: 'Q&A Session',
    name: 'QA Live Stream.mp4',
    type: 'video',
    size: '890 MB',
    creator: 'David Kim',
    avatar: 'https://i.pravatar.cc/40?img=14',
    thumbnail: 'https://picsum.photos/seed/5/400/225',
    platform: 'YouTube',
    views: '0',
    uploadDate: 'Feb 8, 2026',
    uploadedAt: 'Feb 8, 2026',
    uploadedBy: 'David Kim',
    status: 'Under Review',
    duration: '22:10',
    campaign: 'New Feature Announcement',
  },
  {
    id: 6,
    title: 'Product Demo Video',
    name: 'Demo Short.mp4',
    type: 'video',
    size: '23 MB',
    creator: 'Lisa Wang',
    avatar: 'https://i.pravatar.cc/40?img=15',
    thumbnail: 'https://picsum.photos/seed/6/400/225',
    platform: 'TikTok',
    views: '0',
    uploadDate: 'Feb 10, 2026',
    uploadedAt: 'Feb 10, 2026',
    uploadedBy: 'Lisa Wang',
    status: 'Scheduled',
    duration: '1:12',
    campaign: 'Brand Awareness Q1',
  },
];
