"""create users table

Revision ID: 10d19cf59076
Revises: 73ff4b3994d4
Create Date: 2026-02-07 10:32:54.543359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d19cf59076'
down_revision: Union[str, Sequence[str], None] = '73ff4b3994d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('creators', sa.Column('youtube_url', sa.String(), nullable=True))
    op.drop_column('creators', 'portfolio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('creators', 'youtube_url')
    op.drop_column('creators', 'instagram_url')
    # ### end Alembic commands ###
